# Outputting
permalink: /:categories/:year/:month/:day/:title.html

# Conversion
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

# Config for your profile.
title:            APSC1001 & CS1010
name:             APSC1001 & CS1010 Class Website
avatar:           /theme/img/avatar.png

# The theme uses the baseurl throughout, which is useful for running the entire
# site under a subdir, like for this GitHub Pages deployment as a project site.
baseurl: ""

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_pages"]

# Wire in the SASS files in the theme directory.
sass:
  sass_dir: theme/_sass
  style: compressed

# Turn the projects into a collection.
collections:
  assignments:
    output: true
    title: Assignments
    permalink: /:collection/:name.html
  
  labs:
    output: true
    title: Labs
    permalink: /:collection/:name.html

  fall2020_labs:
    output: true
    title: Fall 2020 Labs
    permalink: /:collection/:name.html

defaults:
# Turn the profile sidebar on for all pages by default, except for the
# collections, where it is off and replaced by useful things on the sidebar.
# To override this one a page, use
#    show_profile: false
# to hide the profile.
  -
    scope:
      path: ""
    values:
      show_profile: true
  -
    scope:
      path: "_assignments"
    values:
      show_profile: true
      layout: defaults/assignment
      narrow: true
      due_date: due_date NOT SET

  -
    scope:
      path: "_labs"
    values:
      show_profile: true
      layout: defaults/page
      narrow: true

  -
    scope:
      path: "_fall2020_labs"
    values:
      show_profile: true
      layout: defaults/page
      narrow: true
  
  -
    scope:
      path: "list"
    values:
      show_profile: true
      layout: defaults/list
      narrow: true


